'use strict';
const $=id=>document.getElementById(id), isPig=document.body.dataset.character==='pig', colors=isPig?['yellow','red','orange','purple']:['teal','green','blue','pink'],colorNames=isPig?['노랑','빨강','주황','보라']:['청록','초록','파랑','분홍'];
let round=1,score=0,combo=0,maxCombo=0,pattern=[],position=0,remaining=10000,lives=6,mode='ready',last=0,sound=false,audio;
const buttons=[...document.querySelectorAll('.input')];
function makePattern(){const length=Math.min(48,4+Math.floor((round-1)*1.6));if(isPig){const pairedLength=Math.min(48,length+(length%2));pattern=Array.from({length:pairedLength},(_,i)=>i%2===1?3:round===1?2:Math.floor(Math.random()*3));}else{pattern=Array.from({length},()=>round===1?0:Math.floor(Math.random()*4));}position=0;renderPattern();$('recipe').textContent=['쑥송편','콩송편','깨송편','밤송편'][(round-1)%4];}
function renderPattern(){const root=$('pattern');root.replaceChildren();for(let i=0;i<pattern.length;i+=6){const row=document.createElement('div');row.className='pattern-row';pattern.slice(i,i+6).forEach((c,j)=>{const el=document.createElement('div');el.className='token'+(i+j===position?' current':i+j<position?' done':'');el.dataset.index=i+j;if(isPig&&(i+j)%2===0)el.className+=' paired';const img=document.createElement('img');img.src='assets/'+colors[c]+'.webp';img.alt=colorNames[c];el.append(img);row.append(el);});root.append(row);}}
const drawn={};
function setText(id,value){const text=String(value);if(drawn[id]!==text){$(id).textContent=text;drawn[id]=text;}}
function updateTimer(){setText('time',Math.max(0,remaining/1000).toFixed(1));$('timebar').style.transform=`scaleX(${Math.max(0,remaining/10000)})`;const color=remaining<3000?'#f06c83':'#9283ee';if(drawn.barColor!==color){$('timebar').style.background=color;drawn.barColor=color;}}
function update(){setText('round',round);setText('score',score);setText('combo',combo);if(drawn.lives!==lives){const lifeRoot=$('lives');lifeRoot.replaceChildren();for(let i=0;i<6;i++){const el=document.createElement('span');el.className='life'+(i>=lives?' lost':'');el.textContent='▰';el.setAttribute('aria-hidden','true');lifeRoot.append(el);}lifeRoot.setAttribute('aria-label',`절구 ${lives}개 남음`);drawn.lives=lives;}if(drawn.mode!==mode){buttons.forEach(b=>b.disabled=mode!=='playing');$('pause').disabled=mode!=='playing'&&mode!=='paused';drawn.mode=mode;}updateTimer();}
function animateHit(el,frames){if(el.animate)el.animate(frames,{duration:160,easing:'ease-out'});}
function setOverlay(visible){const overlay=$('overlay');overlay.hidden=!visible;overlay.style.display=visible?'grid':'none';overlay.setAttribute('aria-hidden',String(!visible));}
function start(){round=1;score=0;combo=0;maxCombo=0;remaining=10000;lives=6;mode='playing';last=performance.now();setOverlay(false);$('pause').textContent='일시정지';$('feedback').textContent='위의 순서대로 눌러주세요';makePattern();update();}
function end(){mode='ended';setOverlay(true);$('dialog-title').textContent='떡치기 완료!';$('dialog-body').innerHTML=`송편 <b>${score}개</b> · ROUND ${round}<br>최고 콤보 <b>${maxCombo}</b>`;$('rules').textContent='다시 도전해서 더 많은 송편을 만들어보세요';$('start').textContent='다시 하기';$('feedback').textContent='절구를 모두 잃었어요';update();}
function timeout(){lives--;combo=0;if(lives<=0){lives=0;remaining=0;end();return;}remaining=10000;last=performance.now();makePattern();$('feedback').textContent=`시간 초과! 절구 ${lives}개 남음 · 다시 시작`;update();}
function tone(ok){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=ok?520+(combo%8)*55:140;gain.gain.setValueAtTime(.07,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.11);}catch{}}
function input(c){if(mode!=='playing')return;const now=performance.now();remaining-=now-last;last=now;if(remaining<=0){remaining=0;timeout();return;}const b=buttons.find(x=>Number(x.dataset.color)===c);b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),90);if(pattern[position]===c){position++;combo++;maxCombo=Math.max(combo,maxCombo);tone(true);const actor=document.querySelector('.actor');animateHit(actor,[{transform:'translateX(-50%) translateY(0)'},{transform:'translateX(-50%) translateY(-9px)'},{transform:'translateX(-50%) translateY(0)'}]);if(position===pattern.length){score++;round++;remaining=10000;last=now;$('feedback').textContent='송편 완성!';makePattern();}else{const previous=$('pattern').querySelector(`[data-index="${position-1}"]`);previous.classList.remove('current');previous.classList.add('done');$('pattern').querySelector(`[data-index="${position}"]`).classList.add('current');$('feedback').textContent=`${position} / ${pattern.length}`;}}else{combo=0;tone(false);$('feedback').textContent='틀렸어요! 같은 칸에서 다시';const field=document.querySelector('.field');animateHit(field,[{transform:'translateX(0)'},{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}]);}update();}
function pause(){if(mode==='playing'){remaining-=performance.now()-last;if(remaining<=0){remaining=0;timeout();return;}mode='paused';setOverlay(true);$('dialog-title').textContent='잠깐 쉬는 중';$('dialog-body').textContent=`ROUND ${round} · 송편 ${score}개`;$('rules').textContent='이어서 하면 현재 패턴부터 계속해요';$('start').textContent='이어서 하기';$('pause').textContent='계속하기';}else if(mode==='paused'){mode='playing';last=performance.now();setOverlay(false);$('pause').textContent='일시정지';}update();}
$('start').addEventListener('click',()=>mode==='paused'?pause():start());$('pause').addEventListener('click',pause);const nativeTouch='ontouchstart' in window;let lastPhysicalInput=-Infinity;
buttons.forEach(b=>{const press=()=>{lastPhysicalInput=performance.now();input(Number(b.dataset.color));};if(nativeTouch)b.addEventListener('touchstart',e=>{e.preventDefault();for(const touch of e.changedTouches)press();},{passive:false});b.addEventListener('pointerdown',e=>{if(nativeTouch&&e.pointerType==='touch')return;if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();press();});b.addEventListener('click',e=>{if(e.detail===0&&performance.now()-lastPhysicalInput>500)input(Number(b.dataset.color));});b.addEventListener('contextmenu',e=>e.preventDefault());});document.addEventListener('keydown',e=>{if(e.repeat)return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();input(Number(e.key)-1);}if(e.key==='Escape')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});$('sound').addEventListener('click',()=>{sound=!sound;$('sound').textContent='소리 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기');if(sound)tone(true);});
function tick(now){if(mode==='playing'){remaining=Math.max(0,remaining-(now-last));last=now;if(!remaining)timeout();else updateTimer();}requestAnimationFrame(tick);}makePattern();update();requestAnimationFrame(tick);
const readState=()=>({character:isPig?'pig':'rabbit',mode,round,score,combo,lives,remainingSeconds:Math.max(0,remaining/1000),pattern:pattern.map(c=>colors[c]),position});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_game_state',description:'Read the current tteok game pattern, progress and remaining time.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:readState});document.modelContext.registerTool({name:'start_tteok_game',description:'Start or restart the selected tteok game with six lives and ten seconds per pattern.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{start();return readState();}});}catch{}}

